name: AntiShare
main: com.turt2live.antishare.bukkit.AntiShare
version: maven-version-number
description: Create social awkwardness for creative-mode players
author: turt2live
website: http://dev.bukkit.org/server-mods/antishare
build: jenkins-build-number
commands:
    antishare:
        aliases: [as, ashare, antis, thatgamemodeplugin]
        description: AntiShare core command. See /antishare help for more information
permissions:
    antishare.tools:
        default: op
        description: Allows the use of the AntiShare tools
    antishare.reload:
        default: op
        description: Allows the use of the reload command
    antishare.freeplace:
        default: op
        description: Allows the target to place blocks without tracking
    antishare.freeplace:
        default: op
        description: Allows the target to break blocks regardless of attachments or dis-similar gamemodes
    antishare.freetouch:
        default: op
        description: Allows the target to interact with blocks and entities without inter-gamemode restrictions
    antishare.freeattack:
        default: op
        description: Allows the target to attack entities without inter-gamemode restrictions
    antishare.freeroam:
        default: op
        description: Allows the target to roam free around the worlds, ignoring world splits
    antishare.group.main:
        default: true
        description: Default main group permission
    antishare.alerts:
        default: op
        description: Allows the target to get alerts about naughty actions
    antishare.allow.block_place:
        default: op
        description: Allows all blocks to be placed, regardless of group settings
    antishare.deny.block_place:
        default: false
        description: Denies all blocks to be placed, regardless of group settings
    antishare.allow.block_break:
        default: op
        description: Allows all blocks to be broken, regardless of group settings
    antishare.deny.block_break:
        default: false
        description: Denies all blocks to be broken, regardless of group settings
    antishare.allow.commands:
        default: op
        description: Allows all commands to be used, regardless of group settings
    antishare.deny.commands:
        default: false
        description: Denies all command usage, regardless of group settings
    antishare.allow.interaction:
        default: op
        description: Allows all block interactions, regardless of group settings
    antishare.deny.interaction:
        default: false
        description: Denies all block interactions, regardless of group settings
    antishare.allow.item_use:
        default: op
        description: Allows all item use, regardless of group settings
    antishare.deny.item_use:
        default: false
        description: Denies all item use, regardless of group settings
    antishare.allow.item_drop:
        default: op
        description: Allows all item drops, regardless of group settings
    antishare.deny.item_drop:
        default: false
        description: Denies all item drops, regardless of group settings
    antishare.allow.item_pickup:
        default: op
        description: Allows all item pickups, regardless of group settings
    antishare.deny.item_pickup:
        default: false
        description: Denies all item pickups, regardless of group settings
    antishare.allow.entity_place:
        default: op
        description: Allows all entity placing, regardless of group settings
    antishare.deny.entity_place:
        default: false
        description: Denies all entity placing, regardless of group settings
    antishare.allow.entity_break:
        default: op
        description: Allows all entity breaking, regardless of group settings
    antishare.deny.entity_break:
        default: false
        description: Denies all entity breaking, regardless of group settings
    antishare.allow.entity_attack:
        default: op
        description: Allows all entity attacking, regardless of group settings
    antishare.deny.entity_attack:
        default: false
        description: Denies all entity attacking, regardless of group settings
    antishare.allow.entity_interact:
        default: op
        description: Allows all entity interaction, regardless of group settings
    antishare.deny.entity_interact:
        default: false
        description: Denies all entity interaction, regardless of group settings
    antishare.allow.death:
        default: op
        description: Allows all items to be dropped on death, regardless of group settings
    antishare.deny.death:
        default: false
        description: Denies all items to be dropped on death, regardless of group settings
    antishare.allow.mob_create:
        default: op
        description: Allows all mobs to be created, regardless of group settings
    antishare.deny.mob_create:
        default: false
        description: Denies all mobs to be created, regardless of group settings
