name: AntiShare
main: com.turt2live.antishare.bukkit.AntiShare
version: maven-version-number
description: Create social awkwardness for creative-mode players
author: turt2live
website: http://dev.bukkit.org/server-mods/antishare
build: jenkins-build-number
softdepend: [Vault]
commands:
    antishare:
        aliases: [as, ashare, antis, turt2live]
        description: AntiShare core command. See /antishare help for more information
permissions:
    antishare.tools:
        default: op
        description: Allows the use of the AntiShare tools
    antishare.freeplace:
        default: op
        description: Allows the target to place blocks without tracking
    antishare.group.main:
        default: true
        description: Default main group permission
    antishare.allow.block_place:
        default: op
        description: Allows all blocks to be placed, regardless of group settings
    antishare.alerts:
        default: op
        description: Allows the target to get alerts about naughty actions