# AntiShare Block Configuration
# -------------------------------------------------
# Below are all the settings for the block tracking component
# of AntiShare.
# For more information, please see the following link
# https://docs.google.com/document/d/168QPi5OW6M1dVHOG56iJv_7fgUdNWfUbukWHmNjg_84/edit?usp=sharing
global:
    creative:
    - all
    survival:
    - all
    adventure:
    - none
    spectator:
    - none
    gamemode-settings:
        creative: creative
        survival: survival
        adventure: adventure
        spectator: spectator
    break:
        attachments:
            break-as-placed: true
            default-break: survival
        creative-breaking-survival:
            deny: true
            break-as: creative
        creative-breaking-adventure:
            deny: true
            break-as: creative
        creative-breaking-spectator:
            deny: true
            break-as: creative
        creative-breaking-creative:
            deny: false
            break-as: creative
        survival-breaking-creative:
            deny: true
            break-as: survival
        survival-breaking-adventure:
            deny: true
            break-as: survival
        survival-breaking-spectator:
            deny: true
            break-as: survival
        survival-breaking-survival:
            deny: false
            break-as: survival
        adventure-breaking-creative:
            deny: true
            break-as: adventure
        adventure-breaking-survival:
            deny: true
            break-as: adventure
        adventure-breaking-spectator:
            deny: true
            break-as: adventure
        adventure-breaking-adventure:
            deny: false
            break-as: adventure
        spectator-breaking-creative:
            deny: true
            break-as: spectator
        spectator-breaking-survival:
            deny: true
            break-as: spectator
        spectator-breaking-adventure:
            deny: true
            break-as: spectator
        spectator-breaking-spectator:
            deny: false
            break-as: spectator